version: '3.8'
services:
  proxy:
    restart: unless-stopped
    build:
      context: ./proxy
    ports:
      - "8000:8000"
    depends_on:
      - client
      - mongo
      - server
      - redis
  mongo:
    container_name: mongo-ssm
    image: mongo
    restart: unless-stopped
    volumes:
      - ./.data.prod:/data/db
    command: --quiet
  redis:
    container_name: redis-ssm
    image: redis
    restart: unless-stopped
    volumes:
      - ./.data.redis.prod:/data
    command: --save 60 1
  server:
    restart: unless-stopped
    external_links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    build:
      context: ./server
      additional_contexts:
        - shared-lib=./shared-lib
      target: production
    env_file: .env
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_USER_PWD: ${DB_USER_PWD}
  client:
    restart: unless-stopped
    depends_on:
      - server
    build:
      context: ./client
      additional_contexts:
        - shared-lib=./shared-lib
      target: production
