version: '3.8'
services:
  proxy:
    restart: unless-stopped
    build:
      context: ./proxy
    ports:
      - "8000:8000"
    depends_on:
      - client
      - mongo
      - server
      - redis
  mongo:
    env_file:
      - ./.env.dev
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./.data.dev:/data/db
    command: --quiet
    ports:
      - "${DB_PORT}:27017"
  redis:
    container_name: redis-ssm
    image: redis
    restart: unless-stopped
    volumes:
      - ./.data.redis.dev:/data
    command: --save 60 1
  server:
    restart: unless-stopped
    external_links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    build:
      context: ./server
      additional_contexts:
        - shared-lib=./shared-lib
      target: dev
    env_file:
      - ./.env.dev
    volumes:
      - ./server/src:/server/src
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_USER_PWD: ${DB_USER_PWD}
  client:
    restart: unless-stopped
    environment:
      DEBUG: http-proxy-middleware*
    depends_on:
      - server
    build:
      context: ./client
      additional_contexts:
        - shared-lib=./shared-lib
      target: dev
    volumes:
      - ./client/src:/client/src
      - ./client/config:/client/config
      - ./client/public:/client/public
