- name: Reinstall agent on targeted device
  hosts: all
  become: true
  gather_facts: false
  vars:
    shell_script: undef

  tasks:
    - name: Check out agent
      ansible.builtin.git:
        force: true
        repo: 'https://github.com/SquirrelCorporation/SquirrelServersManager-Agent.git'
        dest: /opt/squirrelserversmanager

    - name: Run Shell Script
      ansible.builtin.shell: "sudo /opt/squirrelserversmanager/install.sh -a -u {{ _ssm_masterNodeUrl }} -s {{ _ssm_deviceId }}"
      register: shell_output
      tags:
        - skip_ansible_lint  # provided variable could require shell modele

    - name: Print script output
      ansible.builtin.debug:
        var: shell_output.stdout_lines

