on:
  pull_request:
    branches:
    - master
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        working-directory: ./server
        run: |
          npm install
          npm run build
          npm test
