on:
  pull_request:
    branches:
    - master

defaults:
  run:
    working-directory: ./server

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run server tests
        run: |
          npm install
          npm run build
          npm test
