on:
  pull_request:
    branches:
    - master
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run server tests
        working-directory: /server
        run: |
          npm install
          npm run build
          npm test
